<a href="https://colab.research.google.com/github/AdicherlaVenkataSai/PyforML/blob/master/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. vector is one dimensional array
2. matrics is two dimensional array
3. tensor is any array greater than 2 dimensions


# Numpy
1. Its a python package for doing math(advance), some special functions(sine, cosine, exponential, sqrt)
2. generating samples from many type of random variables
3. linear algebra, matric multiplication and matric-vector multiplication


In [1]:
import numpy as np  # aliasing 

In [2]:
print(np.cos(np.pi))  # cos(pi) = -1
print(np.sqrt(1.21))  # 1.1
print(np.log(np.exp(5.2)))  # natural log base e with exponetial of number gives the number

-1.0
1.1
5.2


In [4]:
# creating a numpy array
print(np.array([1, 2,3]))  # list to array

# creating matrices
print(np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]]))  # lists to matrix

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
matrix = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
print(matrix.T)  # gives the transpose of it

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
vector1 = np.arange(0,15)  # arange() similar like range , a
vector1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
vector2 = np.arange(0,45,5)  # step size is provided
vector2, print(vector)

[ 0  5 10 15 20 25 30 35 40]


(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40]), None)

In [12]:
# np.linspace(starting pt(included), ending pt(included), no of points reqired(entries))
vector3 = np.linspace(0, 5, 10) 
vector3, print(vector3.reshape(5,2))
# reshape(rows, cols), it returns a matrix but it doesnt update vector
print(vector3)

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [14]:
vector3_reshaped = vector3.reshape(2,5)
vector3_reshaped

array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222],
       [2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]])

In [15]:
random_vector = np.random.randn(15)  # perfect distribution

print(random_vector)
print(random_vector > 0)  # returns the logicals
print(random_vector[random_vector > 0])  # gives only values that satisfies the condition

[ 0.3459246  -1.73742028  0.76746244 -0.19900621 -0.02333282  0.52605082
  0.28529224 -0.3840947  -0.92074286  0.39308439  1.226613    0.94834062
 -0.6498496  -0.43602645 -0.35822431]
[ True False  True False False  True  True False False  True  True  True
 False False False]
[0.3459246  0.76746244 0.52605082 0.28529224 0.39308439 1.226613
 0.94834062]


In [16]:
print(random_vector)
random_vector[random_vector > 0.5] = -5
print(random_vector)

[ 0.3459246  -1.73742028  0.76746244 -0.19900621 -0.02333282  0.52605082
  0.28529224 -0.3840947  -0.92074286  0.39308439  1.226613    0.94834062
 -0.6498496  -0.43602645 -0.35822431]
[ 0.3459246  -1.73742028 -5.         -0.19900621 -0.02333282 -5.
  0.28529224 -0.3840947  -0.92074286  0.39308439 -5.         -5.
 -0.6498496  -0.43602645 -0.35822431]


# Pandas
1. Managing data
2. creates 2 new data types for slicing data: series and dataframe(excel sheet)
3. dataframe is more robust type for storing the data, more flexible than numpy arrays
4. It also has SQL-like functions for merging, joining and sorting dfs


In [17]:
import pandas as pd
import numpy as np

In [21]:
# series is a individual column in a df
mylist = [5.4, 6.1, 1.7, 99.8]
myarray = np.array(mylist)
mylist, myarray

([5.4, 6.1, 1.7, 99.8], array([ 5.4,  6.1,  1.7, 99.8]))

In [22]:
series1 = pd.Series(data = mylist)
print(series1)
series2 = pd.Series(data = myarray)
series2
# here we have same op after converting list, numpy array as Series

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64


0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64

In [23]:
series1[2]  # accessing using indexs

1.7

In [27]:
# we can change the indexs
mylabels = ['red', 'white', 'blue', 'gray']
series3 = pd.Series(data = mylist, index = mylabels)
series3

red       5.4
white     6.1
blue      1.7
gray     99.8
dtype: float64

In [28]:
# even we can write in this way also
series4 = pd.Series(mylist, mylabels)
series4

red       5.4
white     6.1
blue      1.7
gray     99.8
dtype: float64

In [29]:
# even we can also index using new labels
series4['white']

6.1

In [30]:
# calculation on series
series5 = pd.Series([5.4, 1.1, 8.0, 1.6])
series1 + series5  # adding series 1 and 5

0     10.8
1      7.2
2      9.7
3    101.4
dtype: float64

In [32]:
# axis = 0: rows, axis = 1: cols
# if sort = True it'll be in alphabetical order
df1 = pd.concat([series4,series5], axis = 1, sort = False) 
df1

0    1
0       NaN  5.4
1       NaN  1.1
2       NaN  8.0
3       NaN  1.6
blue    1.7  NaN
gray   99.8  NaN
red     5.4  NaN
white   6.1  NaN

In [33]:
df2 = pd.DataFrame(np.random.randn(5, 5))
df2

0         1         2         3         4
0 -2.439599  0.992980 -1.116229  0.569809  0.486430
1 -0.003604 -1.029446 -0.963195 -0.258401  0.577137
2 -1.580355 -0.195354  2.126427  2.383007 -0.304061
3 -0.410481  0.800014  0.474991 -1.929452 -1.345138
4 -0.171298  0.370756 -0.818376  0.986604 -0.917455

In [42]:
# index = row lables, columns = cols labels
df3 = pd.DataFrame(np.random.randn(5, 5), index = ['first R', 'second R', 'third R', 'fourth R', 'fifth R'], columns = ['first C', 'second C', 'third C', 'fourth C', 'fifth C'])
df3

first C  second C   third C  fourth C   fifth C
first R   0.450254  0.534045  0.108242  0.345111 -0.984193
second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019
third R  -0.277135  2.863420  0.150061 -0.889808  0.359609
fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860
fifth R   0.938875  0.938241  0.085707 -0.608010  1.079726

In [44]:
# accessing individual series in a dataframe
# dataframe is list of list, so we can't directly access the rows using []
print(df3['second C'])  # column [] : it's a series
print(df3[['first C', 'third C']])  # column [] : it's a dataframe

first R     0.534045
second R   -0.724095
third R     2.863420
fourth R   -0.803904
fifth R     0.938241
Name: second C, dtype: float64
           first C   third C
first R   0.450254  0.108242
second R  0.092940 -1.014379
third R  -0.277135  0.150061
fourth R  0.209020  1.410217
fifth R   0.938875  0.085707


In [45]:
# two access rows of a dataframe
df3.loc['first R']

first C     0.450254
second C    0.534045
third C     0.108242
fourth C    0.345111
fifth C    -0.984193
Name: first R, dtype: float64

In [46]:
df3.iloc[0]  # even though we renamed the labels, still we can access with the indexs starting form 0

first C     0.450254
second C    0.534045
third C     0.108242
fourth C    0.345111
fifth C    -0.984193
Name: first R, dtype: float64

In [49]:
df3.loc[['fouth R'], ['second C']]

KeyError: ignored

In [50]:
df3 > 0  # logicals

first C  second C  third C  fourth C  fifth C
first R      True      True     True      True    False
second R     True     False    False     False    False
third R     False      True     True     False     True
fourth R     True     False     True      True     True
fifth R      True      True     True     False     True

In [51]:
df3[df3 > 0]  # prints only the postive vales, other are NAN(negative)

first C  second C   third C  fourth C   fifth C
first R   0.450254  0.534045  0.108242  0.345111       NaN
second R  0.092940       NaN       NaN       NaN       NaN
third R        NaN  2.863420  0.150061       NaN  0.359609
fourth R  0.209020       NaN  1.410217  0.663506  0.635860
fifth R   0.938875  0.938241  0.085707       NaN  1.079726

In [52]:
# modifying the dataframe

# add cols
df3['sixth C'] = np.random.randn(5, 1)
df3

first C  second C   third C  fourth C   fifth C   sixth C
first R   0.450254  0.534045  0.108242  0.345111 -0.984193  0.447488
second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R  -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272

In [53]:
df3.drop('first C', axis =1)  # droping the cols

second C   third C  fourth C   fifth C   sixth C
first R   0.534045  0.108242  0.345111 -0.984193  0.447488
second R -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R   2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938241  0.085707 -0.608010  1.079726 -0.166272

In [55]:
df3.drop('first R', axis =0)  # droping the cols

first C  second C   third C  fourth C   fifth C   sixth C
second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R  -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272

In [56]:
df3
# drop doesnt drop in the main dataframe, it only returned the droped dataframe

first C  second C   third C  fourth C   fifth C   sixth C
first R   0.450254  0.534045  0.108242  0.345111 -0.984193  0.447488
second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R  -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272

In [58]:
# to reflect it, we need to update it 
df4 = df3.drop('first C', axis = 1)  # col deleted
df4

second C   third C  fourth C   fifth C   sixth C
first R   0.534045  0.108242  0.345111 -0.984193  0.447488
second R -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R   2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938241  0.085707 -0.608010  1.079726 -0.166272

In [70]:
df5 = df3.drop('first R', axis = 0)  # row deleted
df5

first C  second C   third C  fourth C   fifth C   sixth C
second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R  -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272

In [71]:
# remianing the dataframes index labels
print(df5.reset_index()) # it does't affect the main dataframe
print(df5)

      index   first C  second C   third C  fourth C   fifth C   sixth C
0  second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
1   third R -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
2  fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
3   fifth R  0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272
           first C  second C   third C  fourth C   fifth C   sixth C
second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R  -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272


In [72]:
# to have the change refelected in the dataframe, use inplace = True
df5.reset_index(inplace = True)
df5

index   first C  second C   third C  fourth C   fifth C   sixth C
0  second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
1   third R -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
2  fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
3   fifth R  0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272

In [73]:
df3.drop('first C', axis = 1, inplace = True)
df3

second C   third C  fourth C   fifth C   sixth C
first R   0.534045  0.108242  0.345111 -0.984193  0.447488
second R -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
third R   2.863420  0.150061 -0.889808  0.359609 -1.669945
fourth R -0.803904  1.410217  0.663506  0.635860 -0.299285
fifth R   0.938241  0.085707 -0.608010  1.079726 -0.166272

In [78]:
# can rename the index
df5['new names'] = ['This', 'is', 'the', 'row']
df5

index   first C  second C  ...   fifth C   sixth C  new names
new names                                ...                               
This       second R  0.092940 -0.724095  ... -0.899019 -0.186058       This
is          third R -0.277135  2.863420  ...  0.359609 -1.669945         is
the        fourth R  0.209020 -0.803904  ...  0.635860 -0.299285        the
row         fifth R  0.938875  0.938241  ...  1.079726 -0.166272        row

[4 rows x 8 columns]

In [79]:
df5.set_index('new names', inplace = True)
df5

index   first C  second C   third C  fourth C   fifth C   sixth C
new names                                                                      
This       second R  0.092940 -0.724095 -1.014379 -1.080622 -0.899019 -0.186058
is          third R -0.277135  2.863420  0.150061 -0.889808  0.359609 -1.669945
the        fourth R  0.209020 -0.803904  1.410217  0.663506  0.635860 -0.299285
row         fifth R  0.938875  0.938241  0.085707 -0.608010  1.079726 -0.166272