<a href="https://colab.research.google.com/github/AdicherlaVenkataSai/PyforML/blob/master/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. vector is one dimensional array
2. matrics is two dimensional array
3. tensor is any array greater than 2 dimensions


# Numpy
1. Its a python package for doing math(advance), some special functions(sine, cosine, exponential, sqrt)
2. generating samples from many type of random variables
3. linear algebra, matric multiplication and matric-vector multiplication


In [2]:
import numpy as np  # aliasing 

In [3]:
print(np.cos(np.pi))  # cos(pi) = -1
print(np.sqrt(1.21))  # 1.1
print(np.log(np.exp(5.2)))  # natural log base e with exponetial of number gives the number

-1.0
1.1
5.2


In [4]:
# creating a numpy array
print(np.array([1, 2,3]))  # list to array

# creating matrices
print(np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]]))  # lists to matrix

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
matrix = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])
print(matrix.T)  # gives the transpose of it

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
vector1 = np.arange(0,15)  # arange() similar like range , a
vector1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
vector2 = np.arange(0,45,5)  # step size is provided
vector2, print(vector2)

[ 0  5 10 15 20 25 30 35 40]


(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40]), None)

In [8]:
# np.linspace(starting pt(included), ending pt(included), no of points reqired(entries))
vector3 = np.linspace(0, 5, 10) 
vector3, print(vector3.reshape(5,2))
# reshape(rows, cols), it returns a matrix but it doesnt update vector
print(vector3)

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [9]:
vector3_reshaped = vector3.reshape(2,5)
vector3_reshaped

array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222],
       [2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]])

In [10]:
random_vector = np.random.randn(15)  # perfect distribution

print(random_vector)
print(random_vector > 0)  # returns the logicals
print(random_vector[random_vector > 0])  # gives only values that satisfies the condition

[-0.00303312 -0.93333845 -0.85902392 -0.42629624 -0.47029055 -0.59773346
 -0.17217695  0.90666157 -0.11701817  0.27748593  2.13810615  1.03392123
  1.2768089   0.16854739  0.28759968]
[False False False False False False False  True False  True  True  True
  True  True  True]
[0.90666157 0.27748593 2.13810615 1.03392123 1.2768089  0.16854739
 0.28759968]


In [11]:
print(random_vector)
random_vector[random_vector > 0.5] = -5
print(random_vector)

[-0.00303312 -0.93333845 -0.85902392 -0.42629624 -0.47029055 -0.59773346
 -0.17217695  0.90666157 -0.11701817  0.27748593  2.13810615  1.03392123
  1.2768089   0.16854739  0.28759968]
[-3.03311825e-03 -9.33338445e-01 -8.59023918e-01 -4.26296238e-01
 -4.70290554e-01 -5.97733460e-01 -1.72176949e-01 -5.00000000e+00
 -1.17018172e-01  2.77485928e-01 -5.00000000e+00 -5.00000000e+00
 -5.00000000e+00  1.68547392e-01  2.87599684e-01]


# Pandas
1. Managing data
2. creates 2 new data types for slicing data: series and dataframe(excel sheet)
3. dataframe is more robust type for storing the data, more flexible than numpy arrays
4. It also has SQL-like functions for merging, joining and sorting dfs


In [12]:
import pandas as pd
import numpy as np

In [13]:
# series is a individual column in a df
mylist = [5.4, 6.1, 1.7, 99.8]
myarray = np.array(mylist)
mylist, myarray

([5.4, 6.1, 1.7, 99.8], array([ 5.4,  6.1,  1.7, 99.8]))

In [14]:
series1 = pd.Series(data = mylist)
print(series1)
series2 = pd.Series(data = myarray)
series2
# here we have same op after converting list, numpy array as Series

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64


0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64

In [15]:
series1[2]  # accessing using indexs

1.7

In [16]:
# we can change the indexs
mylabels = ['red', 'white', 'blue', 'gray']
series3 = pd.Series(data = mylist, index = mylabels)
series3

red       5.4
white     6.1
blue      1.7
gray     99.8
dtype: float64

In [17]:
# even we can write in this way also
series4 = pd.Series(mylist, mylabels)
series4

red       5.4
white     6.1
blue      1.7
gray     99.8
dtype: float64

In [18]:
# even we can also index using new labels
series4['white']

6.1

In [19]:
# calculation on series
series5 = pd.Series([5.4, 1.1, 8.0, 1.6])
series1 + series5  # adding series 1 and 5

0     10.8
1      7.2
2      9.7
3    101.4
dtype: float64

In [20]:
# axis = 0: rows, axis = 1: cols
# if sort = True it'll be in alphabetical order
df1 = pd.concat([series4,series5], axis = 1, sort = False) 
df1

0    1
0       NaN  5.4
1       NaN  1.1
2       NaN  8.0
3       NaN  1.6
blue    1.7  NaN
gray   99.8  NaN
red     5.4  NaN
white   6.1  NaN

In [21]:
df2 = pd.DataFrame(np.random.randn(5, 5))
df2

0         1         2         3         4
0  0.914682  0.470832  0.951208  1.887976  0.204011
1  1.079866 -1.041780 -1.084888  0.624126  0.410688
2 -1.889438  0.605756 -0.994759 -1.471385  0.549526
3 -0.904066 -0.169683 -0.813442  1.349411  0.689150
4  0.532224  0.637817  1.300404  1.948607  1.519273

In [22]:
# index = row lables, columns = cols labels
df3 = pd.DataFrame(np.random.randn(5, 5), index = ['first R', 'second R', 'third R', 'fourth R', 'fifth R'], columns = ['first C', 'second C', 'third C', 'fourth C', 'fifth C'])
df3

first C  second C   third C  fourth C   fifth C
first R   0.102460  1.920491 -1.305816 -0.269105  0.790597
second R -0.189728  0.996689 -0.741356  0.227088  1.187489
third R  -2.199147  1.317541 -0.267268 -0.510097  0.248813
fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272
fifth R   1.427292  0.257247  0.929275  0.973147 -0.805985

In [23]:
# accessing individual series in a dataframe
# dataframe is list of list, so we can't directly access the rows using []
print(df3['second C'])  # column [] : it's a series
print(df3[['first C', 'third C']])  # column [] : it's a dataframe

first R     1.920491
second R    0.996689
third R     1.317541
fourth R    0.888772
fifth R     0.257247
Name: second C, dtype: float64
           first C   third C
first R   0.102460 -1.305816
second R -0.189728 -0.741356
third R  -2.199147 -0.267268
fourth R  0.024197  0.758566
fifth R   1.427292  0.929275


In [24]:
# two access rows of a dataframe
df3.loc['first R']

first C     0.102460
second C    1.920491
third C    -1.305816
fourth C   -0.269105
fifth C     0.790597
Name: first R, dtype: float64

In [25]:
df3.iloc[0]  # even though we renamed the labels, still we can access with the indexs starting form 0

first C     0.102460
second C    1.920491
third C    -1.305816
fourth C   -0.269105
fifth C     0.790597
Name: first R, dtype: float64

In [26]:
#df3.loc[['fouth R'], ['second C']]

In [27]:
df3 > 0  # logicals

first C  second C  third C  fourth C  fifth C
first R      True      True    False     False     True
second R    False      True    False      True     True
third R     False      True    False     False     True
fourth R     True      True     True      True    False
fifth R      True      True     True      True    False

In [28]:
df3[df3 > 0]  # prints only the postive vales, other are NAN(negative)

first C  second C   third C  fourth C   fifth C
first R   0.102460  1.920491       NaN       NaN  0.790597
second R       NaN  0.996689       NaN  0.227088  1.187489
third R        NaN  1.317541       NaN       NaN  0.248813
fourth R  0.024197  0.888772  0.758566  0.548187       NaN
fifth R   1.427292  0.257247  0.929275  0.973147       NaN

In [29]:
# modifying the dataframe

# add cols
df3['sixth C'] = np.random.randn(5, 1)
df3

first C  second C   third C  fourth C   fifth C   sixth C
first R   0.102460  1.920491 -1.305816 -0.269105  0.790597 -0.320070
second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R  -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817

In [30]:
df3.drop('first C', axis =1)  # droping the cols

second C   third C  fourth C   fifth C   sixth C
first R   1.920491 -1.305816 -0.269105  0.790597 -0.320070
second R  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R   1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   0.257247  0.929275  0.973147 -0.805985 -0.574817

In [31]:
df3.drop('first R', axis =0)  # droping the cols

first C  second C   third C  fourth C   fifth C   sixth C
second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R  -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817

In [32]:
df3
# drop doesnt drop in the main dataframe, it only returned the droped dataframe

first C  second C   third C  fourth C   fifth C   sixth C
first R   0.102460  1.920491 -1.305816 -0.269105  0.790597 -0.320070
second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R  -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817

In [33]:
# to reflect it, we need to update it 
df4 = df3.drop('first C', axis = 1)  # col deleted
df4

second C   third C  fourth C   fifth C   sixth C
first R   1.920491 -1.305816 -0.269105  0.790597 -0.320070
second R  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R   1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   0.257247  0.929275  0.973147 -0.805985 -0.574817

In [34]:
df5 = df3.drop('first R', axis = 0)  # row deleted
df5

first C  second C   third C  fourth C   fifth C   sixth C
second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R  -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817

In [35]:
# remianing the dataframes index labels
print(df5.reset_index()) # it does't affect the main dataframe
print(df5)

      index   first C  second C   third C  fourth C   fifth C   sixth C
0  second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
1   third R -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
2  fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
3   fifth R  1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817
           first C  second C   third C  fourth C   fifth C   sixth C
second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R  -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817


In [36]:
# to have the change refelected in the dataframe, use inplace = True
df5.reset_index(inplace = True)
df5

index   first C  second C   third C  fourth C   fifth C   sixth C
0  second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
1   third R -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
2  fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
3   fifth R  1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817

In [37]:
df3.drop('first C', axis = 1, inplace = True)
df3

second C   third C  fourth C   fifth C   sixth C
first R   1.920491 -1.305816 -0.269105  0.790597 -0.320070
second R  0.996689 -0.741356  0.227088  1.187489 -0.855786
third R   1.317541 -0.267268 -0.510097  0.248813 -1.816064
fourth R  0.888772  0.758566  0.548187 -2.081272 -0.272258
fifth R   0.257247  0.929275  0.973147 -0.805985 -0.574817

In [38]:
# can rename the index
df5['new names'] = ['This', 'is', 'the', 'row']
df5

index   first C  second C  ...   fifth C   sixth C  new names
0  second R -0.189728  0.996689  ...  1.187489 -0.855786       This
1   third R -2.199147  1.317541  ...  0.248813 -1.816064         is
2  fourth R  0.024197  0.888772  ... -2.081272 -0.272258        the
3   fifth R  1.427292  0.257247  ... -0.805985 -0.574817        row

[4 rows x 8 columns]

In [39]:
df5.set_index('new names', inplace = True)
df5

index   first C  second C   third C  fourth C   fifth C   sixth C
new names                                                                      
This       second R -0.189728  0.996689 -0.741356  0.227088  1.187489 -0.855786
is          third R -2.199147  1.317541 -0.267268 -0.510097  0.248813 -1.816064
the        fourth R  0.024197  0.888772  0.758566  0.548187 -2.081272 -0.272258
row         fifth R  1.427292  0.257247  0.929275  0.973147 -0.805985 -0.574817

# Combining Dataframes
The waus dataframes are combined in pandas is similar to SQL

1. concat
2. join
3. merge

In [40]:
df7 = pd.DataFrame({'customer':['101', '102', '103', '104']
                     , 'category':['cat2', 'cat2', 'cat1', 'cat3']
                     , 'important':['yes', 'no', 'yes', 'yes']
                     , 'sales':[123, 52, 214, 663]
                     })  # index = [0, 1, 2, 3]

                    
df8 = pd.DataFrame({'customer':['101', '103', '104', '105']
                     , 'color':['yellow', 'green', 'green', 'blue']
                     , 'distance':[12, 9, 44, 21]
                     , 'sales':[123, 214, 663, 331]
                     })  # index = [4, 5, 6, 7]

In [41]:
# combining the two dataframes
pd.concat([df7, df8], axis= 0, sort = False)

# the category variable is not in df8, those places are having NaNs

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
0      101      NaN       NaN    123  yellow      12.0
1      103      NaN       NaN    214   green       9.0
2      104      NaN       NaN    663   green      44.0
3      105      NaN       NaN    331    blue      21.0

In [42]:
pd.concat([df7, df8], axis= 0, sort = True)
# organises cols in aplhabetical order

category   color customer  distance important  sales
0     cat2     NaN      101       NaN       yes    123
1     cat2     NaN      102       NaN        no     52
2     cat1     NaN      103       NaN       yes    214
3     cat3     NaN      104       NaN       yes    663
0      NaN  yellow      101      12.0       NaN    123
1      NaN   green      103       9.0       NaN    214
2      NaN   green      104      44.0       NaN    663
3      NaN    blue      105      21.0       NaN    331

In [43]:
pd.concat([df7, df8], axis= 1, sort = False)
# concats works on index values
# putting df7, df8 sibe by side by their index value

customer category important  sales customer   color  distance  sales
0      101     cat2       yes    123      101  yellow        12    123
1      102     cat2        no     52      103   green         9    214
2      103     cat1       yes    214      104   green        44    663
3      104     cat3       yes    663      105    blue        21    331

In [44]:
df7 = pd.DataFrame({'customer':['101', '102', '103', '104']
                     , 'category':['cat2', 'cat2', 'cat1', 'cat3']
                     , 'important':['yes', 'no', 'yes', 'yes']
                     , 'sales':[123, 52, 214, 663]
                     }, index = [0, 1, 2, 3])  # 

                    
df8 = pd.DataFrame({'customer':['101', '103', '104', '105']
                     , 'color':['yellow', 'green', 'green', 'blue']
                     , 'distance':[12, 9, 44, 21]
                     , 'sales':[123, 214, 663, 331]
                     }, index = [4, 5, 6, 7])  # 

In [45]:
pd.concat([df7, df8], axis= 0, sort = False)

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
4      101      NaN       NaN    123  yellow      12.0
5      103      NaN       NaN    214   green       9.0
6      104      NaN       NaN    663   green      44.0
7      105      NaN       NaN    331    blue      21.0

In [46]:
pd.concat([df7, df8], axis= 0, sort = True)

category   color customer  distance important  sales
0     cat2     NaN      101       NaN       yes    123
1     cat2     NaN      102       NaN        no     52
2     cat1     NaN      103       NaN       yes    214
3     cat3     NaN      104       NaN       yes    663
4      NaN  yellow      101      12.0       NaN    123
5      NaN   green      103       9.0       NaN    214
6      NaN   green      104      44.0       NaN    663
7      NaN    blue      105      21.0       NaN    331

In [47]:
pd.concat([df7, df8], axis= 1, sort = False)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

### merge and join
merge combines dataframes using a col's values to identify common entries

join combines dataframes using the index to identify common entires

In [48]:
import numpy as np
import pandas as pd

df7 = pd.DataFrame({'customer':['101', '102', '103', '104']
                     , 'category':['cat2', 'cat2', 'cat1', 'cat3']
                     , 'important':['yes', 'no', 'yes', 'yes']
                     , 'sales':[123, 52, 214, 663]
                     }, index = [0, 1, 2, 3])  # 

                    
df8 = pd.DataFrame({'customer':['101', '103', '104', '105']
                     , 'color':['yellow', 'green', 'green', 'blue']
                     , 'distance':[12, 9, 44, 21]
                     , 'sales':[123, 214, 663, 331]
                     }, index = [4, 5, 6, 7])  # 

pd.merge(df7, df8, how = 'outer', on = 'customer')  # outer merge is union of on 
# if we have same variable in both, they will be represented as sales_x, sales_y for sales

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [49]:
pd.merge(df7, df8, how = 'inner', on = 'customer')  # intersection
# we dont have NaN in inner merge

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [50]:
pd.merge(df7, df8, how = 'left', on = 'customer') 
# gives all rows from first dataframe i.e: df7

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow      12.0    123.0
1      102     cat2        no       52     NaN       NaN      NaN
2      103     cat1       yes      214   green       9.0    214.0
3      104     cat3       yes      663   green      44.0    663.0

In [51]:
pd.merge(df7, df8, how = 'right', on = 'customer') 
# gives all rows from second dataframe i.e: df8

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

"merge" combines the column values, whereas "join" combines the index values

In [55]:
df9 = pd.DataFrame({'Q1': [101, 102, 103]
                    , 'Q2': [201, 202, 203]}
                    , index = ['I0', 'I1', 'I2'])

df10 = pd.DataFrame({'Q3': [301, 302, 303]
                    , 'Q4': [401, 402, 403]}
                    , index = ['I0', 'I2', 'I3'])


In [56]:
# join behaves just like merge
# except instead of using the values of one of the columns
# to combine data frames,it uses the index labels

df9.join(df10, how ='outer')

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2  103.0  203.0  302.0  402.0
I3    NaN    NaN  303.0  403.0

In [57]:
df9.join(df10, how ='outer')

Q1   Q2   Q3   Q4
I0  101  201  301  401
I2  103  203  302  402

In [59]:
df9.join(df10, how ='left')

Q1   Q2     Q3     Q4
I0  101  201  301.0  401.0
I1  102  202    NaN    NaN
I2  103  203  302.0  402.0

In [60]:
df9.join(df10, how ='right')

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

# Functionalities of PANDAS

In [62]:
#  Series

df8['color'].unique()  # all unique values

array(['yellow', 'green', 'blue'], dtype=object)

In [64]:
#Series
df8['color'].value_counts()  # no of times the labels show up

green     2
blue      1
yellow    1
Name: color, dtype: int64

In [65]:
# Series
df9.mean()  # to cal the mean of the dataframe

Q1    102.0
Q2    202.0
dtype: float64

In [66]:
df8.columns  # list of col names

Index(['customer', 'color', 'distance', 'sales'], dtype='object')

In [67]:
df8  # to cross check

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [68]:
# we can create a new df using the series
new_df = df8[(df8['customer'] != '105') & (df8['color'] != 'green')]
new_df

customer   color  distance  sales
4      101  yellow        12    123

In [71]:
# mean, std, sum, min of the series
print(df8['sales'].mean())
print(df8['distance'].min())
print(df8['sales'].std())
print(df8['sales'].sum())

332.75
9
236.05419575456256
1331


In [72]:
def profit(s):
  return s * 0.5

In [73]:
df8['sales'].apply(profit)  # apply() allows to use the user defined funtion 

4     61.5
5    107.0
6    331.5
7    165.5
Name: sales, dtype: float64

In [75]:
df8['color'].apply(len)  
# applying the predined function
# as we cant direclty apply the len function on the series

4    6
5    5
6    5
7    4
Name: color, dtype: int64

In [76]:
# applymap ,allows to apply a function to entire dataset, 
# only works on df, and entry by entry
# and output is also a df
df11 = df8[['distance', 'sales']]
df11.applymap(profit)

distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5

In [77]:
def col_sum(co):
  return sum(co)
df11.apply(col_sum)

distance      86
sales       1331
dtype: int64

In [78]:
del df8['color']  # we can delete a series from the df

In [79]:
df8

customer  distance  sales
4      101        12    123
5      103         9    214
6      104        44    663
7      105        21    331

In [80]:
df8.index

Int64Index([4, 5, 6, 7], dtype='int64')

In [82]:
# we can sort acccording to var
df8.sort_values(by = 'distance', inplace = True)
# if  inplace =  true, them it reflects in the actual d

In [85]:
# if some series has mulitple of the same values then we can group all the unique entries together
mydict = {'customer':['customer1', 'customer1', 'customer2', 'customer2','customer3', 'customer3']
          , 'product1': [1.1, 2.1, 3.8, 4.2, 5.5, 6.9]
          ,  'product2': [8.2, 9.1, 11.1, 5.2, 44.66, 983]}

df6 = pd.DataFrame(mydict, index = ['purchase 1', 'purchase 2', 'purchase 3', 'purchase 4', 'purchase 5', 'purchase 6'])
df6


customer  product1  product2
purchase 1  customer1       1.1      8.20
purchase 2  customer1       2.1      9.10
purchase 3  customer2       3.8     11.10
purchase 4  customer2       4.2      5.20
purchase 5  customer3       5.5     44.66
purchase 6  customer3       6.9    983.00

In [86]:
grouped_data = df6.groupby('customer')
grouped_data

In [87]:
grouped_data.describe()

product1                      ... product2                        
             count mean       std  min  ...      25%     50%      75%    max
customer                                ...                                 
customer1      2.0  1.6  0.707107  1.1  ...    8.425    8.65    8.875    9.1
customer2      2.0  4.0  0.282843  3.8  ...    6.675    8.15    9.625   11.1
customer3      2.0  6.2  0.989949  5.5  ...  279.245  513.83  748.415  983.0

[3 rows x 16 columns]

In [89]:
print(grouped_data.std())
print(grouped_data.mean())

           product1    product2
customer                       
customer1  0.707107    0.636396
customer2  0.282843    4.171930
customer3  0.989949  663.506577
           product1  product2
customer                     
customer1       1.6      8.65
customer2       4.0      8.15
customer3       6.2    513.83


# PANDAS saving and loading DF's

In [90]:
# saving the dataframe using to_csv(name we need to save, mentioning index will also save it in seperate col)
df8.to_csv('df8.csv', index = True)

In [94]:
new_df = pd.read_csv('df8.csv')
new_df  
# can see here, indexs are also stored
# creates an index, as were not mentioning what is index

Unnamed: 0  customer  distance  sales
0           5       103         9    214
1           4       101        12    123
2           7       105        21    331
3           6       104        44    663

In [96]:
new_df1 = pd.read_csv('df8.csv', index_col = 0)  #telling that first col is indes
new_df1

# even we can use other varibales as the index col

customer  distance  sales
5       103         9    214
4       101        12    123
7       105        21    331
6       104        44    663

In [97]:
df8.to_excel('df8.xlsx', index=False, sheet_name = 'first sheet')
# to the excel sheet, not mentioning the index, and creating in the first sheet


In [99]:
new_df2 = pd.read_excel('df8.xlsx', sheet_name = 'first sheet')
new_df2

customer  distance  sales
0       103         9    214
1       101        12    123
2       105        21    331
3       104        44    663

In [100]:
new_df3 = pd.read_excel('df8.xlsx', sheet_name = 'first sheet', index_col = 0)
new_df3  # customer acts as a index and its no longer a column

distance  sales
customer                 
103              9    214
101             12    123
105             21    331
104             44    663